"""empty message

Revision ID: 2611be85274c
Revises: None
Create Date: 2015-01-27 02:50:53.542407

"""

# revision identifiers, used by Alembic.
revision = '2611be85274c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('github', sa.String(), nullable=False),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('scheduled_for'),
    sa.UniqueConstraint('twitter')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    ### end Alembic commands ###
