"""empty message

Revision ID: 5cfae648270
Revises: None
Create Date: 2015-01-24 02:50:58.266335

"""

# revision identifiers, used by Alembic.
revision = '5cfae648270'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    ### end Alembic commands ###
